matrix:
- name: Markdown
  sources:
  - '**/*.md'
  default_encoding: utf-8
  aspell:
    lang: en
    d: en_GB
  dictionary:
    wordlists:
    - wordlist.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
  - pyspelling.filters.html:
      comments: false
      ignores:
      - code
      - pre