# Basic
name:               "Jessica White"

author:
  name:             Jessica White
  twitter:          JessPWhite
  github:           wordshaker
  linkedin:         jessica-white-67917883
  email:            jess@womenintechnotts.co.uk

# Google-analytics
google-analytics:
  id:               ""

# URL
url:                "http://www.jesswhite.co.uk/" # the base hostname & protocol for your site
baseurl:            "" # the subpath of your site, e.g. /blog

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           GMT
permalink:          /:year-:month-:day/:title/

# Pagination
paginate:           5
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  imput:            GFM

# Navigation
nav:
  - name:           "Blog"
    url:            "/"    
  - name:           "Abstracts"
    url:            "/abstracts"        
  - name:           "About"
    url:            "/about"
  - name:           "WiTNotts"
    url:            "/witnotts"
  - name:           "Archive"
    url:            "/archive"

# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
gems:
  - jekyll-seo-tag
  - jekyll-paginate

exclude:            [vendor]
