plugins:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-paginate

exclude:
  - "/vendor/"

# Site settings
title: Jessica White - Blog
#subtitle: "A simple yet classy theme for your Jekyll website or blog"
email: me@jesswhite.co.uk
name: Jessica White
description:  >
  All views and opinions expressed in this blog are my own and do not reflect the views of my employer.
baseurl: "" 
url: "" 
cover: "/assets/header_image.jpg"
logo: "/assets/logo.png"

# Build settings
markdown: kramdown
paginate: 10
paginate_path: "/page:num/"
inter_post_navigation: false
highlightjs_theme: "monokai-sublime"

# Archive settings (see https://github.com/jekyll/jekyll-archives/)
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: 'archive'
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'

# Google analytics
ga_tracking_id: "UA-156892072-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: jekyll
    desc: "Posts describing Jekyll setup techniques."

# Social

social:
  - name: Twitter
    icon: twitter
    username: JessPWhite
    url: https://twitter.com/JessPWhite
    desc: Follow me on Twitter
    share: true

  - name: GitHub
    icon: github
    username: wordshaker
    url: https://github.com/wordshaker
    desc: Fork me on GitHub
    share: false

  - name: LinkedIn
    icon: linkedin
    username: Jessica White
    url: https://www.linkedin.com/in/jessica-white-67917883
    desc: Connect with me on LinkedIn
    share: true

protocols:
    twitter_image: "/assets/logo.png"

permalink: /:year/:month/:day/:title:output_ext