title: Jessica White - Blog
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my blog! Includes write ups of hacks & conferences attended, tech tried out
  and general musings.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Jessica White # add your name
author-img: jess-white.jpg # add your photo
about-author: I am a developer focusing on back-end development with a passion for monitoring. Always hungry to keep learning. Founder of Women In Tech Nottingham
twitter: JessPWhite
speakerbase: jessica-white
github: wordshaker
linkedin: jessica-white-67917883
email: me@jesswhite.co.uk

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

future: true
