title: Jessica White - Blog
description: >
  Welcome to my blog! Includes write ups of hacks & conferences attended, tech tried out
  and general musings.
permalink: ':title/'
baseurl: "" 
url: "" 

# Author Settings
author: Jessica White 
author-img: jess-white.jpg
about-author: I am a software developer at UNiDAYS, international speaker & avid learner. Topics that I am is particularly interested include community building & all aspects of monitoring. Founder of Women In Tech Nottingham. I am easily bribed with coffee & love hearing about other people’s experiences in technology. Opinions are my own and not the views of my employer.
twitter: JessPWhite
speakerbase: jessica-white
github: wordshaker
linkedin: jessica-white-67917883
email: me@jesswhite.co.uk

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

future: true
