name: Build

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [ '2.6', '2.7' ]

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"

    - name: Set up Ruby
      uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - name: Install packages
      continue-on-error: true
      run: |
        gem install type-on-strap
        gem install jekyll-theme-type-on-strap
        docker pull sylhare/type-on-strap
        docker pull sylhare/jekyll

    - name: Build
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec jekyll build
