name: Spellcheck Action

on:
  pull_request:
    paths:
    - '**.txt'
    - '**.md'

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: rojopolis/spellcheck-github-actions@0.24.0
      name: Spellcheck
      with:
        source_files: README.md CHANGELOG.md
        task_name: Markdown
        output_file: spellcheck-output.txt

    - uses: actions/upload-artifact@v3
      name: Archive spellcheck output
      with:
        name: Spellcheck artifact
        path: spellcheck-output.txt