name: JessWhite Deploy

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    
    - name: Build
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        jekyll build
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'jesswhite'
        publish_dir: ./site
        publish-profile: ${{ secrets.AzurePublishProfile }}