name: jesswhite
on:
  push:
    branches:
      - master
jobs:
  build_deploy:
    runs-on: ubuntu-18.04
    steps:
  steps:
      - uses: actions/checkout@master
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.x' # Version range or exact version of a Ruby version to use, using semvers version range syntax.
      - run: ruby hello.rb
      - name: up
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          ruby hello.rb \
          gem install jekyll \
          jekyll build \
          aws s3 cp \
            --recursive \
            --acl public-read \
            --region eu-west-1 \ 
            ./_site/ [s3://jesswhite/] 
