name: jesswhite
on:
  push:
    branches:
      - master
jobs:
  build_deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: up
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          gem install jekyll
          jekyll build
          aws s3 cp \
            --recursive \
            --acl public-read \
            --region eu-west-1 \ 
            ./_site/ [s3://jesswhite/] 
